### ISSUE TITLE
下载了项目看了下，你这只是使用了casbin的库，但是在验证时貌似并没有使用casbin的model

### ISSUE THREAD

**Issue by phpxcn** [pl1998/laravel-casbin-admin#12]
下载了项目看了下，你这只是使用了casbin的库，但是在验证时貌似并没有使用casbin的model
![image](https://user-images.githubusercontent.com/1595447/148202249-8c3a698e-c2d6-4278-92c1-cf34637274a0.png)

**Comment by pl1998** [comment]
嗯 对的

**Comment by phpxcn** [comment]
我现在自己想试着去用Enforcer::enforce ，但是一直在报错
local.ERROR: array_combine(): Both parameters should have an equal number of elements {"userId":9,"exception":"[object] (ErrorException(code: 0): array_combine(): Both parameters should have an equal number of elements at /Users/ly/www/laravel-admin/vendor/casbin/casbin/src/CoreEnforcer.php:645

**Comment by phpxcn** [comment]
![image](https://user-images.githubusercontent.com/1595447/148321835-424f54b4-97e3-461f-b959-15c0857d7abc.png)
![image](https://user-images.githubusercontent.com/1595447/148321863-4d9791ce-08d9-4e69-ae68-ba812929750e.png)
![image](https://user-images.githubusercontent.com/1595447/148321927-3526e755-22ad-4b36-80e8-cadb0daabc59.png)

我修改了下，这里这样的话就可以使用casbin了

**Comment by pl1998** [comment]
可以了 牛

**Comment by pl1998** [comment]
可以的 牛
