### ISSUE TITLE
not support PHP8.0.1

### ISSUE THREAD

**Issue by shine96** [pl1998/laravel-casbin-admin#6]
![image](https://user-images.githubusercontent.com/58157887/120754002-a31a8300-c53e-11eb-9808-e355b5b5959a.png)

**Comment by pl1998** [comment]
rm -rf composer.lock 然后重新composer install

**Comment by shine96** [comment]
ok ,采用了
![image](https://user-images.githubusercontent.com/58157887/120754239-f8ef2b00-c53e-11eb-8961-f06daa5eafb9.png)
