### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by my-autoxuexi** [pl1998/laravel-casbin-admin#7]
npm ERR! code 1
npm ERR! path Z:\Codes\laravel-casbin-admin\laravel-casbin-admin\node_modules\node-pty
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node scripts/install.js

**Comment by pl1998** [comment]
```
npm i -g npm
```
这种npm install 的 问题可以自己百度的 `npm ERR! code 1`
