### ISSUE TITLE
通配符的那种是怎么验证的？

### ISSUE THREAD

**Issue by sparksisnotspark** [pl1998/laravel-casbin-admin#9]
api/log/:id/del或api/log/{id}/del这种的。是如何实现验证的？
![image](https://user-images.githubusercontent.com/13254289/126455214-a346ae31-d930-4328-b58f-37f83c9ccbae.png)
你验证的逻辑是这个样子，从数据库里取出来，与uri来比对？这样子可以么？因为下载了这个之后没有跑起来，但我又用到我的项目里了，现在。。。。我使用的不是laravel,，逻辑比照你代码重写的

**Comment by pl1998** [comment]
你使用的是thinkphp吗? 你就按照你使用的框架方法将路由重写下 应该差异不会很大的 稍微调整一下逻辑 然后在后台改下路由就行了

**Comment by pl1998** [comment]
![image](https://user-images.githubusercontent.com/43993206/126473708-1c9795e3-ec21-48e1-b75a-174533c70e74.png)
举个例子 把这个改成你想对应的路由

**Comment by sparksisnotspark** [comment]
是这样子的，我们没有使用这些框架，使用的是自己公司写的一个框架，然后路由的方式也是不一样的，我最终的解决方式是你之前差不多，只是如果是通配型的话，自己想办法重新比对了一下，差不多这样子，laravel可以直接儿取uri，可以直接使用，




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月21日(星期三) 晚上6:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pl1998/laravel-casbin-admin] 通配符的那种是怎么验证的？ (#9)





 

 把这个改成你想对应的路由

**Comment by hsluoyz** [comment]
@sparksisnotspark Casbin对不同类型的路径有内置的支持：https://casbin.org/docs/zh-CN/function ，启用keyMatch2或keyMatch3，然后调用Enforce函数检查权限即可

![image](https://user-images.githubusercontent.com/3787410/126582163-7b722e8f-4e23-47fd-849f-55086cc0e257.png)

**Comment by sparksisnotspark** [comment]
哎，为了快速搞完项目，没有仔细看文档。谢谢你




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yang ***@***.***&gt;; 
发送时间: 2021年7月22日(星期四) 上午10:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pl1998/laravel-casbin-admin] 通配符的那种是怎么验证的？ (#9)





 
@sparksisnotspark Casbin对不同类型的路径有内置的支持：https://casbin.org/docs/zh-CN/function ，启用keyMatch2或keyMatch3，然后调用Enforce函数检查权限即可
